# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    volumes: 
      - default:/db
    environment:
      POSTGRES_PASSWORD: 12341234
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 5433:8080

volumes:
  default:
